arb-dir: assets/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json
output-class: AppLocalizations
output-dir: lib/l10n